---
title: "Metricas de Performance"
output:
  html_document:
    toc: yes
    toc_float: yes
    number_sections: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r ,echo=FALSE,include=FALSE}
library(ggplot2)
library(plotly)
library(dplyr)
library(gridExtra)
library(DSutilsR)
library(yardstick)
theme_set(theme_grey())
```
<br/><br/>

# Información adicional

```{r ,echo=FALSE}
M
```

# Metricas de Performance

```{r ,echo=FALSE,include=FALSE,warning=FALSE}
res <- eval_binary_performance(Y,pred)
```

### Valores Generales

```{r ,echo=FALSE}
M <- matrix(ncol=3,nrow=2)
M[1,] <- round(c(res$auc,res$ks,res$tpr),3)
M[2,] <- c(1,1,1) 
colnames(M) <- c("AUC","KS","tpr")
t(M[1,c(1,2,3)]) %>% kable(escape = F, align = "c") %>%
  kable_styling(c("striped", "condensed"), full_width = F)
```

**Grafica Curva de ROC**

```{r ,echo=FALSE,warning=FALSE,fig.width = 7, fig.height = 5, fig.show = "hold"}
InformationValue::plotROC(Y,pred)
```

**Gráfica Curva de Lift Acumulada**

```{r ,echo=FALSE,warning=FALSE,fig.width = 7, fig.height = 5, fig.show = "hold"}
plot(res$plot_lift)
```


**Grafica KS**

```{r ,echo=FALSE,warning=FALSE,fig.width = 7, fig.height = 5, fig.show = "hold"}
plot(res$plot_ks)
```

**Matriz de confusion por threshold**

```{r ,echo=FALSE,out.width="50%",message=FALSE}

# grafico matriz de consusion

plot_confusion_matrix <- function(Y,pred,tresh){
  df <- data.frame(Y,pred) %>% mutate(Y=if_else(Y==1,"Yes","No") %>% as.factor(),
                                      pred=if_else(pred>tresh,"Yes","No") %>% as.factor())
  cm <- conf_mat(df,Y,pred)
  autoplot(cm, type = "heatmap")+scale_fill_gradient(low="#D6EAF8",high = "#2E86C1")+ggtitle(paste0("Confusion Matrix treshold: ",tresh))
}

```

```{r ,echo=FALSE,out.width="60%",message=FALSE}

# graficos por treshold

L <- seq(0.1,0.9,0.1) %>% purrr::map(~plot_confusion_matrix(df_test$chd,df_test$prob,.x))
L
```
